### ISSUE TITLE
build 2.7.5 on osx-arm64

### ISSUE THREAD

**Issue by LunarLanding** [conda-forge/mathjax-feedstock#16]
https://anaconda.org/conda-forge/mathjax does not list osx-arm64 for version 2.7.5.
This specific version is used by plotly whose packages depend on. 
These packages are build already for osx-arm64 but can't be installed because mathjax does not provide 2.7.5 on this platform.
Can a build be added for this version?

**Comment by m-rossi** [comment]
I ran into the same issue. I forked the recipe, created a branch `2.7` and built a package for osx-arm64. You can install it from my anaconda channel with `conda install -c mrossi mathjax=2.7`

If @conda-forge/mathjax can create a branch pointing at 707ab63f35cd16703acd0a25fc0f7615aa98a9d0 I can open a PR to add an osx-arm64 package for the `2.7.*` versions.

**Comment by tdegeus** [comment]
If that is the case I think that `potly` should update!!! Out of curiosity, why cannot it run with a new `mathjax`? Also `mathjax` does not seem to be a dependency here https://github.com/conda-forge/plotly-feedstock ?

That being said, I'm not strictly against adding a build of `2.7.5`. But only if it is absolutely necessary. Is there a way that this can be done from anywhere else than the main branch, because I'm not too keen of temporarily adapting it? 

If it is indeed absolutely necessary and there is a good way, yes, please @m-rossi a PR would be very much appreciated.

**Comment by m-rossi** [comment]
> If that is the case I think that `potly` should update!!! Out of curiosity, why cannot it run with a new `mathjax`? Also `mathjax` does not seem to be a dependency here https://github.com/conda-forge/plotly-feedstock ?

It's not base `plotly` it is [Kaleido](https://github.com/plotly/Kaleido) for exporting static images from plotly figures. I agree they should upgrade, see the related issue here: https://github.com/plotly/Kaleido/issues/124. The [version-pin](https://github.com/conda-forge/kaleido-core-feedstock/blob/main/recipe/meta.yaml#L51) is done in the [kaleido-core-feedstock](https://github.com/conda-forge/kaleido-core-feedstock)

> That being said, I'm not strictly against adding a build of `2.7.5`. But only if it is absolutely necessary. Is there a way that this can be done from anywhere else than the main branch, because I'm not too keen of temporarily adapting it?
> 
> If it is indeed absolutely necessary and there is a good way, yes, please @m-rossi a PR would be very much appreciated.

May my post above was not clear enough. You, as feedstock maintainer, can create a branch e.g. `v2` with 707ab63f35cd16703acd0a25fc0f7615aa98a9d0 as reference and then I can create a PR with the necessary changes against that branch, see [Maintaining several versions](https://conda-forge.org/docs/maintainer/updating_pkgs.html?#maintaining-several-versions)

**Comment by m-rossi** [comment]
@tdegeus Any thoughts?

**Comment by tdegeus** [comment]
Sorry @m-rossi it slipped my attention. The branch sounds great. I've created it with the said reference : https://github.com/conda-forge/mathjax-feedstock/tree/v2 . Looking forward to your PR

**Comment by tdegeus** [comment]
Fixed by https://github.com/conda-forge/mathjax-feedstock/pull/19
