### ISSUE TITLE
Upload v2 failed

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/mathjax-feedstock#20]
### Comment:

@m-rossi Do you know why the upload of v2 failed with error `Authorization token is no longer valid`? Do you think it is just a glitch for which I should restart the CI, or is there another issue?

**Comment by m-rossi** [comment]
It may have to do with those tokens in the older version? https://github.com/conda-forge/mathjax-feedstock/blob/v2/conda-forge.yml

The main branch does not have these tokens, they where removed with [this commit](https://github.com/conda-forge/mathjax-feedstock/commit/8870c714ec8e4b0c001a1cb55067c3fa2c76f961). ~~Please try to remove them.~~ I removed them in #23.

**Comment by m-rossi** [comment]
Looks like removal of tokens solved it, I see new packages on anaconda.org. I'm sorry I overlooked this change in #19.

**Comment by tdegeus** [comment]
Thanks! Your PR has solved the issue. I can get v2.7.7 on my macOS/ARM now
